// LOOKUP nodemailer

// CREATE ACCOUNT MANAGEMENT

// HTTP CREATE ACCOUNT OK
// LATER after creation user gets a confirmation mail
POST http://localhost:6006/api/v1/account/new
content-type: application/json

{
	"username": "muwella",
	"email": "marielabrascon@mail.com",
	"password": "3A84%pMHoygK"
}

###

// HTTP CREATE ACCOUNT | Username not available
POST http://localhost:6006/api/v1/account/new
content-type: application/json

{
	"username": "muwella",
	"email": "availableEmail@mail.com",
	"password": "somethinG123"
}

###

// HTTP CREATE ACCOUNT | Email not available
POST http://localhost:6006/api/v1/account/new
content-type: application/json

{
	"username": "availableUsername",
	"email": "marielabrascon@mail.com",
	"password": "somethinG123"
}

###

# HTTP CONFIRM ACCOUNT
// LATER user cannot create recipes until account is confirmed
PATCH http://localhost:3001/api/v1/account/confirmation/638ffd43a76fd0d67b9fd89d

###

// HTTP DEACTIVATE ACCOUNT
// LATER after deactivation user gets an email with recover account link
PATCH http://localhost:3001/api/v1/account/deactivate
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4ZmZkNDNhNzZmZDBkNjdiOWZkODlkIiwiaWF0IjoxNjcwMzgxMTIyfQ.jN7PtSxEhDLWxQX0Zi5AkGRhmUfoF74XB9PmPjL7KX0

###

// HTTP RECOVER ACCOUNT (ACTIVATE)
// LATER user should get this link on mail
PATCH http://localhost:3001/api/v1/account/recoverAccount/638ffd43a76fd0d67b9fd89d