# HTTP get categories
GET http://localhost:3001/api/v1/categories/
content-type: application/json

### 

// NOTE no se usa
# get category by id
# GET http://localhost:3001/api/v1/categories/636e98a4847f5d6c2d6aaae5
# content-type: application/json

###

# HTTP create category
POST http://localhost:3001/api/v1/categories/new
content-type: application/json

{
	"name": "Party",
	"creator_id": "637c32a01bb1e745c5fac1df"
}

###

# HTTP update all (developtment)
# fields are added or removed on all documents
PUT http://localhost:3001/api/v1/categories/updateAll
content-type: application/json

{
	"new_field": {
		"type": "unset",
	}
}

###

# HTTP update category
PATCH http://localhost:3001/api/v1/categories/update/636e98a4847f5d6c2d6aaae5
content-type: application/json

{
	"name": "Party food"
}

###

# HTTP delete category
DELETE http://localhost:3001/api/v1/categories/delete/636e98a4847f5d6c2d6aaae5
content-type: application/json