// PRODUCTION

// HTTP CREATE RECIPE
POST http://localhost:6006/api/v1/recipes/new
content-type: application/json
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNhMDljNjYxZmQwNDE2YmQxZTM0MWM5IiwiaWF0IjoxNjcxNDcxMTI3fQ.h8yw6iI9XvPBQwdfn7duhR2BGrnFsPsKKxMEWusZRWQ
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM5NjNiMDNmYjdjMjRlYjhmOGZmMWIwIiwiaWF0IjoxNjcwNzkwMDkyfQ.Ybu1dRflLqIAgEyvAt3bozZmjrLQ0J-uYsLvtvX6uuI

{
	"name": "Recipe 2345",
	"category": ["63a5ff21c7163c510dccb003"]
}

###

// HTTP CREATE RECIPE | Category does not exist
POST http://localhost:6006/api/v1/recipes/new
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM5NjNiMDNmYjdjMjRlYjhmOGZmMWIwIiwiaWF0IjoxNjcwNzkwMDkyfQ.Ybu1dRflLqIAgEyvAt3bozZmjrLQ0J-uYsLvtvX6uuI

{
	"name": "Mini pizzas",
	"category": ["639df9a120eed72e7edf90cb"]
}

###

// HTTP GET RECIPES
GET http://localhost:6006/api/v1/recipes/
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNhMDljNjYxZmQwNDE2YmQxZTM0MWM5IiwiaWF0IjoxNjcxNDcxMTI3fQ.h8yw6iI9XvPBQwdfn7duhR2BGrnFsPsKKxMEWusZRWQ

###

// HTTP GET RECIPES | QUERY CATEGORY
GET http://localhost:6006/api/v1/recipes?category=Party
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM5NjNiMDNmYjdjMjRlYjhmOGZmMWIwIiwiaWF0IjoxNjcwNzkwMDkyfQ.Ybu1dRflLqIAgEyvAt3bozZmjrLQ0J-uYsLvtvX6uuI

###

// HTTP GET RECIPES | QUERY SEARCH_TEXT
GET http://localhost:6006/api/v1/recipes?search_text=oli
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM5NjNiMDNmYjdjMjRlYjhmOGZmMWIwIiwiaWF0IjoxNjcwNzkwMDkyfQ.Ybu1dRflLqIAgEyvAt3bozZmjrLQ0J-uYsLvtvX6uuI

###

// HTTP GET RECIPES | QUERY CATEGORY and SEARCH_TEXT
GET http://localhost:6006/api/v1/recipes?category=Party&search_text=oli
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM5NjNiMDNmYjdjMjRlYjhmOGZmMWIwIiwiaWF0IjoxNjcwNzkwMDkyfQ.Ybu1dRflLqIAgEyvAt3bozZmjrLQ0J-uYsLvtvX6uuI

###

// HTTP GET RECIPE SUGGESTIONS
GET http://localhost:3001/api/v1/recipes/suggestions
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjY5Njg4NDcyfQ.2Ce7p0zgDK6A182va_Am1WYDA7wTqWf4Q-UwRogQ0NM

###

# HTTP GET LAST ADDED RECIPES
GET http://localhost:6006/api/v1/recipes/lastAdded
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjY5Njg4NDcyfQ.2Ce7p0zgDK6A182va_Am1WYDA7wTqWf4Q-UwRogQ0NM

###

# HTTP GET RECIPE
GET http://localhost:6006/api/v1/recipes/63856d9f60686e61107219f9
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjY5Njg4NDcyfQ.2Ce7p0zgDK6A182va_Am1WYDA7wTqWf4Q-UwRogQ0NM

###

# HTTP UPDATE RECIPE
PATCH http://localhost:6006/api/v1/recipes/update/639c7b25461f920cb457ddab
content-type: application/json
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjY5Njg4NDcyfQ.2Ce7p0zgDK6A182va_Am1WYDA7wTqWf4Q-UwRogQ0NM
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM5NjNiMDNmYjdjMjRlYjhmOGZmMWIwIiwiaWF0IjoxNjcwNzkwMDkyfQ.Ybu1dRflLqIAgEyvAt3bozZmjrLQ0J-uYsLvtvX6uuI

{
	"category": ["639f838bf3792b69acdd119a"]
}

###

# HTTP DELETE RECIPE
DELETE http://localhost:6006/api/v1/recipes/delete/63a0a43d038a49fd1a946ad5
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM5NjNiMDNmYjdjMjRlYjhmOGZmMWIwIiwiaWF0IjoxNjcwNzkwMDkyfQ.Ybu1dRflLqIAgEyvAt3bozZmjrLQ0J-uYsLvtvX6uuI
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNhMDljNjYxZmQwNDE2YmQxZTM0MWM5IiwiaWF0IjoxNjcxNDcxMTI3fQ.h8yw6iI9XvPBQwdfn7duhR2BGrnFsPsKKxMEWusZRWQ


// DEVELOPMENT

# HTTP UPDATE RECIPES
PUT http://localhost:6006/api/v1/recipes/updateAll
content-type: application/json

{
}

###

# HTTP DELETE RECIPES
PUT http://localhost:6006/api/v1/recipes/deleteAll
content-type: application/json