// PRODUCTION

# HTTP CREATE RECIPE
POST http://localhost:3001/api/v1/recipes/new
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjcwMjYwODc4fQ.C3303bRBrUZFNFZpM01q-nA92vRwFy57cd4lyJaTBUw

{
	"name": "New recipe shawtyy"
}

###

# HTTP GET RECIPES
GET http://localhost:3001/api/v1/recipes/
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjcwMjYwODc4fQ.C3303bRBrUZFNFZpM01q-nA92vRwFy57cd4lyJaTBUw

###

# HTTP GET RECIPE SUGGESTIONS
GET http://localhost:3001/api/v1/recipes/suggestions
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjY5Njg4NDcyfQ.2Ce7p0zgDK6A182va_Am1WYDA7wTqWf4Q-UwRogQ0NM

###

# HTTP GET LAST ADDED RECIPES
GET http://localhost:3001/api/v1/recipes/lastAdded
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjY5Njg4NDcyfQ.2Ce7p0zgDK6A182va_Am1WYDA7wTqWf4Q-UwRogQ0NM

###

# HTTP GET RECIPE
GET http://localhost:3001/api/v1/recipes/63856d9f60686e61107219f9
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjY5Njg4NDcyfQ.2Ce7p0zgDK6A182va_Am1WYDA7wTqWf4Q-UwRogQ0NM

###

# HTTP UPDATE RECIPE
PATCH http://localhost:3001/api/v1/recipes/update/63856d9f60686e61107219f9
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjY5Njg4NDcyfQ.2Ce7p0zgDK6A182va_Am1WYDA7wTqWf4Q-UwRogQ0NM

{
	"name": "Super Awesome Banana Split",
	"ingredients": ["Ice Cream", "Chocolate Syrup", "Banana", "Sprinkles"]
}

###

# HTTP DELETE RECIPE
DELETE http://localhost:3001/api/v1/recipes/delete/63856d9f60686e61107219f9
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4NTZjOTg2MDY4NmU2MTEwNzIxOWVkIiwiaWF0IjoxNjY5Njg4NDcyfQ.2Ce7p0zgDK6A182va_Am1WYDA7wTqWf4Q-UwRogQ0NM


// DEVELOPMENT

# HTTP UPDATE RECIPES
PUT http://localhost:3001/api/v1/recipes/updateAll
content-type: application/json

{
}

###

# HTTP DELETE RECIPES
PUT http://localhost:3001/api/v1/recipes/deleteAll
content-type: application/json