GET http://localhost:3000/api/v1/users/111
content-type: application/json

###

POST http://localhost:3000/api/v1/recipes/new
content-type: application/json

{
    "name": "pasta",
    "quality": 10, 
    "type": "meal"
}

###

PATCH http://localhost:3000/api/v1/recipes/partialUpdate/111
content-type: application/json

{
    "name": "patched recipe",
    "quality": 10, 
    "type": "meal"
}

###

DELETE http://localhost:3000/api/v1/recipes/delete/111
content-type: application/json