// PRODUCTION

// HTTP GET USER (SELF)
GET http://localhost:3001/api/v1/users/me
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4ZTY5OWUyYWE2NGRkZmNmZjQ3ZTUzIiwiaWF0IjoxNjcwMjc3NTkxfQ.IGKEgw3HtyGJNgiuMVVcDLhxH8Lcl-QrP34s06zKPw0

###

// HTTP UPDATE USER
PATCH http://localhost:3001/api/v1/users/me/update
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4ZTY5OWUyYWE2NGRkZmNmZjQ3ZTUzIiwiaWF0IjoxNjcwMjc3NTkxfQ.IGKEgw3HtyGJNgiuMVVcDLhxH8Lcl-QrP34s06zKPw0

{
	"name": "ada"
}

### -------------------- ###

// DEVELOPTMENT

// HTTP GET ALL USERS
GET http://localhost:3001/api/v1/users/
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4ZTY5OWUyYWE2NGRkZmNmZjQ3ZTUzIiwiaWF0IjoxNjcwMjc3NTkxfQ.IGKEgw3HtyGJNgiuMVVcDLhxH8Lcl-QrP34s06zKPw0

### 

// HTTP UPDATE ALL
// fields are added or removed on all documents
PUT http://localhost:3001/api/v1/users/updateAll
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4ZTY5OWUyYWE2NGRkZmNmZjQ3ZTUzIiwiaWF0IjoxNjcwMjc3NTkxfQ.IGKEgw3HtyGJNgiuMVVcDLhxH8Lcl-QrP34s06zKPw0

{
	"account_confirmed": {
		"type": "set"
	}
}

###

// HTTP DELETE USER
DELETE http://localhost:3001/api/v1/users/me/delete

###

// HTTP DELETE ALL
PUT http://localhost:3001/api/v1/users/deleteAll

### -------------------- ###

// FOR FUTURE VERSIONS

// HTTP ADD USER TO FRIENDS

// HTTP GET FRIENDS

// HTTP REMOVE USER FROM FRIENDS