# HTTP get users
GET http://localhost:3001/api/v1/users/
content-type: application/json

### 

# HTTP get user by id
GET http://localhost:3001/api/v1/users/637c32a01bb1e745c5fac1df
content-type: application/json

###

# HTTP create user
POST http://localhost:3001/api/v1/users/new
content-type: application/json

{
	"username": "peppa pig",
	"email": "perfect",
	"password": "anotherSuperPassword"
}

###

# HTTP update all (development)
# fields are added or removed on all documents
PUT http://localhost:3001/api/v1/users/updateAll
content-type: application/json

{
	"new_field": {
		"type": "unset",
	}
}

###

# HTTP update user
PATCH http://localhost:3001/api/v1/users/update/637c35cfbad54ffd19285730
content-type: application/json

{
	"name": "Peppa oink"
}

###

// PICK UP HERE
# HTTP delete user
DELETE http://localhost:3001/api/v1/users/delete/637c35cfbad54ffd19285730
content-type: application/json